version: '3'


services:
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./integration_trial:/recommendation
    ports:
      - 8000:8000
    links:
      - db
  db:
    image: mongo
    restart: always
    container_name: 'mongo'
    command: mongod
    volumes: 
      - ./db:/data/db
    ports:
      - 27017:27017
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
        - 8081:8081
    depends_on: 
      - db          